export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE"
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS"
export const GLOBAL = {
    USER_LOGIN : "USER_LOGIN",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE : "USER_LOGIN_FAILURE",
    USER_REGISTRATION_FAILURE : "USER_REGISTRATION_FAILURE",
    USER_REGISTRATION_SUCCESS : "USER_REGISTRATION_SUCCESS"
}